### ISSUE TITLE
[BUG]玩家在低头的时候派蒙会遮挡玩家视线，并且无法放置和破坏方块

### ISSUE THREAD

**Issue by CiclesMiao** [MikhailTapio/Paimon#1]
我的世界版本1.20.1

模组列表：
Forge 47.2.18
Curios API 5.4.7
**Paimon 1.0.0**

问题：玩家在低头的时候派蒙会遮挡玩家视线，并且无法放置和破坏方块

如图：
![image](https://github.com/MikhailTapio/Paimon/assets/103619120/6eca7a9d-9198-4858-9894-54395fe230f8)
![image](https://github.com/MikhailTapio/Paimon/assets/103619120/9a96a734-dc72-4933-80cb-fa19d5839439)

**Comment by VulpesStella** [comment]
已在 1.0.1 修复，CurseForge 上传中
