### ISSUE TITLE
[BUG] Paimon Medal Slot does not exist (MC 1.19.2, FORGE)

### ISSUE THREAD

**Issue by ManuEcheveste** [MikhailTapio/Paimon#2]
Hi,
I'm unable to use the Paimon Medal, as there is no slot to use it as shown in the image below:

![image](https://github.com/MikhailTapio/Paimon/assets/47963698/c2f98c06-87d9-43e0-a0d6-77322124db19)

The only slot available is the "Charm" slot.

Details of programs and related are:

- Minecraft 1.19.2 (unable to use a newer minecraft version due to compatibility with other mods).
- Paimon Mod 1.0.6 (replicated with 1.0.5)
- Curios API 1.19.2-5.1.6.1 (replicated with 1.19.2-5.1.4.4)
- Forge 43.3.8 (replicated with 43.3.0)

The slot for the medal doesn't exist when using the modpack I was trying to make, however, it still doesn't work when using only the Paimon and the API mods, resetting the config files and everything.

For the time being, I'll need to stick to an older version of the Paimon mod that still uses the charm slot.

If more information is needed, please let me know.

**Comment by VulpesStella** [comment]
Thx for reporting, I'll look into it very soon.

**Comment by VulpesStella** [comment]
Fixed in 1.0.7.
